apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: ollama
spec:
  dnsNames:
    - argocd.my-code-chat-bot.ch
  secretName: letsencrypt-nginx-argocd-private-key
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer