apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-nginx0
spec:
  acme:
    email: sadig@gmx.ch
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx0
    solvers:
      - http01:
          ingress:
            class: nginx
