apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ollama-cert
  namespace: ollama
spec:
  dnsNames:
    - my-code-chat-bot.ch
  secretName: letsencrypt-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer