
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: ollama
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-nginx
    # kubernetes.io/tls-acme: 'true'
    # nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    # nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
spec:
  tls:
  - hosts:
    - www.my-code-chat-bot.ch
    secretName: letsencrypt-nginx
  # - hosts:
  #   - www.argocd.my-code-chat-bot.ch
  #   secretName: letsencrypt-nginx-argocd-private-key
# # kubectl get secret -n ollama and use here the one with type kubernetes.io/tls
  rules:
    - host: www.my-code-chat-bot.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama-webui-svc
                port:
                  number: 8080
    # - host: www.argocd.my-code-chat-bot.ch
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: argocd-server
    #             port:
    #               name: https
  ingressClassName: nginx
