apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ollama-cert0
  namespace: ollama
spec:
  dnsNames:
    - www.coding-assistant.ch
  secretName: ollama-letsencrypt-tls0
  issuerRef:
    name: letsencrypt-nginx0
    kind: ClusterIssuer
