apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-nginx-ingress
  namespace: ollama
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-nginx"
spec:
  tls:
  - hosts:
    - www.coding-assistant.ch
    secretName: ollama-letsencrypt-tls
  ingressClassName: nginx
  rules:
    - host: www.coding-assistant.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama-webui-svc
                port:
                  number: 8080
  

 
