apiVersion: networking.k8s.io/v1
kind: Ingress
# metadata:
#   name: nginx-ingress
#   namespace: ollama
#   annotations:
#     cert-manager.io/cluster-issuer: "letsencrypt-nginx"
#     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
# spec:
#   tls:
#   - hosts:
#     - my-code-chat-bot.ch
#     secretName: letsencrypt-tls
#   ingressClassName: nginx
#   rules:
#     - host: my-code-chat-bot.ch
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: ollama-webui-svc
#                 port:
#                   number: 8080
  
metadata:
  name: nginx-ingress
  namespace: ollama
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  tls:
  - hosts:
    - www.my-code-chat-bot.ch
    secretName: letsencrypt-nginx-private-key
  rules:
    - host: www.my-code-chat-bot.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama-webui-svc
                port:
                  number: 8080
  ingressClassName: nginx
 
