apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ollama-cert
  namespace: ollama
spec:
  dnsNames:
    - www.coding-assistant.ch
  secretName: ollama-letsencrypt-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
